USE db_travels_java;
SHOW TABLES FROM db_travels_java;

SELECT * FROM db_travels_java.travels;

INSERT INTO db_travels_java.travels (expense, vendor, amount) VALUES ("Travel Charger", "ACDC Outlets", 49.95);
INSERT INTO db_travels_java.travels (expense, vendor, amount) VALUES ("Ohana Instruments", "Sunscreen", 11.71);
INSERT INTO db_travels_java.travels (expense, vendor, amount) VALUES ("Huge Plastic Flamingo Floatie", "Party City", 77.89);
INSERT INTO db_travels_java.travels (expense, vendor, amount) VALUES ("4 Manapua", "Manapua Man", 8.00)


